# Dados de conexão com o banco H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  # Configuração do cliente web do banco H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuração para mostrar o SQL no console
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/test-migration

springdoc:
  swagger-ui:
    path: /docs-hotelmanagement.html
  api-docs:
    path: /api-hotelmanagement

docflow:
  title: Hotel Management API
  version: 1.0.0
  description: Hotel Management is a backend REST API designed to support the core operations of a hotel chain.
  default-error-schema: io.github.mateussilva.hotelmanagement.shared.handlers.CustomError